### ISSUE TITLE
Update travis for python 3.7 and 3.8

### ISSUE THREAD

**Issue by mnarayan** [skggm/skggm#130]
- [ ] Fix the build for xenial and later distributions. Likely need to eliminate installation of libatlas3gf-base.  Also see updates to travis configuration for [sklearn 0.22](https://github.com/scikit-learn/scikit-learn/blob/0.22.X/.travis.yml)
- [ ] Add support for python 3.7 
- [ ] Add support for python 3.8

**Comment by mnarayan** [comment]
Note the following combinations do not produce build errors shown below. 
`platform linux -- Python 3.6.3, pytest-3.3.0, py-1.5.2, pluggy-0.6.0`
`platform linux -- Python 3.6.9, pytest-4.6.4, py-1.8.1, pluggy-0.13.1`
```
Traceback (most recent call last):
  File "/home/user/.local/bin/pytest", line 5, in <module>
    from pytest import main
  File "/home/user/.local/lib/python3.6/site-packages/pytest.py", line 13, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/home/user/.local/lib/python3.6/site-packages/_pytest/fixtures.py", line 839, in <module>
    class FixtureFunctionMarker(object):
  File "/home/user/.local/lib/python3.6/site-packages/_pytest/fixtures.py", line 841, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))
TypeError: attrib() got an unexpected keyword argument 'convert'
```
