### ISSUE TITLE
Installation requirements

### ISSUE THREAD

**Issue by camiel-m** [skggm/skggm#132]
Hi,

I'm very interested in using your Graphical Lasso implementation due to the possibility of adding a matrix penalty (not included in sklearn). However, I'm having some issues installing the git repo. The installation finishes fine in a new environment (py3.6.13) but depending on test method there are a number of packages with the wrong version. An example is sklearn which seems to be required to be <0.20 due to the graph_lasso renaming (more examples below).

Would it be possible to share a .yml file of a working environment or some more detailed package requirements?

```
> python -m pytest inverse_covariance
Traceback (most recent call last):
  File "/XXX/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/XXX/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/XXX/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/XXX/lib/python3.6/site-packages/pytest-6.2.2-py3.6.egg/pytest/__init__.py", line 3, in <module>
    from . import collect
  File "/XXX/lib/python3.6/site-packages/pytest-6.2.2-py3.6.egg/pytest/collect.py", line 8, in <module>
    from _pytest.deprecated import PYTEST_COLLECT_MODULE
  File "/XXX/lib/python3.6/site-packages/pytest-6.2.2-py3.6.egg/_pytest/deprecated.py", line 13, in <module>
    from _pytest.warning_types import PytestDeprecationWarning
  File "/XXX/lib/python3.6/site-packages/pytest-6.2.2-py3.6.egg/_pytest/warning_types.py", line 6, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
```

```
> python plot_functional_brain_networks.py 
Traceback (most recent call last):
  File "plot_functional_brain_networks.py", line 20, in <module>
    from nilearn import datasets, plotting, input_data
  File "/XXX/lib/python3.6/site-packages/nilearn-0.7.0-py3.6.egg/nilearn/__init__.py", line 67, in <module>
    _check_module_dependencies()
  File "/XXX/lib/python3.6/site-packages/nilearn-0.7.0-py3.6.egg/nilearn/version.py", line 127, in _check_module_dependencies
    install_info=module_metadata.get('install_info'))
  File "/XXX/lib/python3.6/site-packages/nilearn-0.7.0-py3.6.egg/nilearn/version.py", line 73, in _import_module_with_version_check
    module = __import__(module_name)
ModuleNotFoundError: No module named 'nibabel'. Module "nibabel" could not be found. Please install it properly to use nilearn.
```

My environment:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
blas                      1.1                    openblas    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py36h5fab9bb_1    conda-forge
cython                    0.29.22          py36hc4f0c31_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           1_h86c2bf4_netlib    conda-forge
libcblas                  3.9.0           3_h92ddd45_netlib    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
liblapack                 3.9.0           3_h92ddd45_netlib    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nilearn                   0.7.0                    pypi_0    pypi
nose                      1.3.7                    pypi_0    pypi
numpy                     1.19.5           py36h2aa4a07_1    conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.1.1j               h7f98852_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pytest                    6.2.2                    pypi_0    pypi
python                    3.6.13          hffdb5ce_0_cpython    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
scikit-learn              0.19.2          py36_blas_openblasha84fab4_201  [blas_openblas]  conda-forge
scipy                     1.5.3            py36h9e8f40b_0    conda-forge
seaborn                   0.11.1                   pypi_0    pypi
setuptools                49.6.0           py36h5fab9bb_3    conda-forge
skggm                     0.2.8                    pypi_0    pypi
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
```

**Comment by Vlasovets** [comment]
hello!
I would like to join in asking help for "skggm" installation.
I created an environment with python 3.6.13 as @camiel-m mentioned before, also requirements.txt is satisfied, but I'm still getting the error below. 
Would be great if you can point if I do something wrong.
Thank you in advance!


```
Building wheel for skggm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/oleg.vlasovetc/opt/anaconda3/envs/gglasso/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/gk/5cmhr9sj39n2byqq6c12k44jy8nkk3/T/pip-install-9pbaydun/skggm_fc6da6e8f932473db7b3f5b44e7cc7bd/setup.py'"'"'; __file__='"'"'/private/var/folders/gk/5cmhr9sj39n2byqq6c12k44jy8nkk3/T/pip-install-9pbaydun/skggm_fc6da6e8f932473db7b3f5b44e7cc7bd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/gk/5cmhr9sj39n2byqq6c12k44jy8nkk3/T/pip-wheel-i489ijzj
       cwd: /private/var/folders/gk/5cmhr9sj39n2byqq6c12k44jy8nkk3/T/pip-install-9pbaydun/skggm_fc6da6e8f932473db7b3f5b44e7cc7bd/ 
```

**Comment by MaximilienGaudette** [comment]
Hey, I'm having the same problem here while trying to import --≥ from inverse_covariance import QuicGraphLasso. There are a bunch of packages that seem to be deprecated. Even if I fix this one with an older version of Scikit-Learn, I get another error message. Any clue on this?

Thank you in advance.
